name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-execute-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js latest 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Show my SoftUni username
      run: echo "myro.97"

  build-and-execute-ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-execute-unit-tests
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js latest 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Start app in background
      run: npm start &
    - name: Execute UI tests
      run: npm run test:ui